// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw4o52dTkmTWHnZmxu1F6U0CEv-VRsQnY',
    appId: '1:146337042716:web:b363900f7693ebd0c86ad9',
    messagingSenderId: '146337042716',
    projectId: 'appproject-7306a',
    authDomain: 'appproject-7306a.firebaseapp.com',
    databaseURL: 'https://appproject-7306a.firebaseio.com',
    storageBucket: 'appproject-7306a.appspot.com',
    measurementId: 'G-F2Z0K66BDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2w2qz0NQx8D026oHqtvJS09Gl8efLdfM',
    appId: '1:146337042716:android:d6ce5d08cb7d7449c86ad9',
    messagingSenderId: '146337042716',
    projectId: 'appproject-7306a',
    databaseURL: 'https://appproject-7306a.firebaseio.com',
    storageBucket: 'appproject-7306a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDevjkup-jeuQkzX9NpMPnWbUILyK6oA_8',
    appId: '1:146337042716:ios:93047fe506f2eb45c86ad9',
    messagingSenderId: '146337042716',
    projectId: 'appproject-7306a',
    databaseURL: 'https://appproject-7306a.firebaseio.com',
    storageBucket: 'appproject-7306a.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDevjkup-jeuQkzX9NpMPnWbUILyK6oA_8',
    appId: '1:146337042716:ios:93047fe506f2eb45c86ad9',
    messagingSenderId: '146337042716',
    projectId: 'appproject-7306a',
    databaseURL: 'https://appproject-7306a.firebaseio.com',
    storageBucket: 'appproject-7306a.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw4o52dTkmTWHnZmxu1F6U0CEv-VRsQnY',
    appId: '1:146337042716:web:b363900f7693ebd0c86ad9',
    messagingSenderId: '146337042716',
    projectId: 'appproject-7306a',
    authDomain: 'appproject-7306a.firebaseapp.com',
    databaseURL: 'https://appproject-7306a.firebaseio.com',
    storageBucket: 'appproject-7306a.appspot.com',
    measurementId: 'G-F2Z0K66BDZ',
  );

}